services:
  integrisight-backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development

  integrisight-frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://localhost:8000
      - CLARITY_PROJECT_ID=${CLARITY_PROJECT_ID:-}
